services:
  page-docs-postgresql:
    image: bitnami/postgresql:latest
    container_name: page-docs-postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      # - POSTGRESQL_PASSWORD=1234567
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_TIMEZONE=Asia/Shanghai # 数据库时区设置为上海时间
      - POSTGRESQL_LOG_TIMEZONE=Asia/Shanghai # 日志时区设置为上海时间 # 设置时区为上海，这个非常重要，不然写入的时间相较于北京时间会少 8 小时
    volumes:
      - ./postgresql_data:/bitnami/postgresql

networks:
  default:
    name: page-docs-network
    driver: bridge
